AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'saasable.gemspec'

Metrics/AbcSize:
  Exclude:
    - 'lib/saasable/mongoid/scoped_document.rb'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Exclude:
    - 'lib/saasable/mongoid/saas_document.rb'
    - 'lib/saasable/mongoid/scoped_document.rb'
    - 'lib/saasable/railties/helpers.rb'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
Style/RescueModifier:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
# SupportedStyles: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
