# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: saasable 4.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "saasable"
  s.version = "4.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Educa2", "Rafael Gaspar"]
  s.date = "2014-07-17"
  s.description = "A gem for making a Multi-Tenant SaaS using Mongoid"
  s.email = "suporte@educa2.com.br"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/saasable.rb",
    "lib/saasable/errors.rb",
    "lib/saasable/middleware.rb",
    "lib/saasable/mongoid.rb",
    "lib/saasable/mongoid/saas_document.rb",
    "lib/saasable/mongoid/scoped_document.rb",
    "lib/saasable/railtie.rb",
    "lib/saasable/railties.rb",
    "lib/saasable/railties/helpers.rb",
    "saasable.gemspec",
    "spec/saasable_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/educa2/saasable"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A gem for making a Multi-Tenant SaaS using Mongoid"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, ["~> 4.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, ["~> 4.0.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, ["~> 4.0.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
  end
end

