# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: saasable 6.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "saasable".freeze
  s.version = "6.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Eadbox".freeze, "Rafael Gaspar".freeze]
  s.date = "2019-06-04"
  s.description = "A gem for making a Multi-Tenant SaaS using Mongoid".freeze
  s.email = "suporte@eadbox.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/saasable.rb",
    "lib/saasable/errors.rb",
    "lib/saasable/middleware.rb",
    "lib/saasable/mongoid.rb",
    "lib/saasable/mongoid/saas_document.rb",
    "lib/saasable/mongoid/scoped_document.rb",
    "lib/saasable/railtie.rb",
    "lib/saasable/railties.rb",
    "lib/saasable/railties/helpers.rb",
    "saasable.gemspec",
    "spec/saasable_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/eadbox/saasable".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "A gem for making a Multi-Tenant SaaS using Mongoid".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>.freeze, [">= 6.0"])
      s.add_runtime_dependency(%q<nokogiri>.freeze, [">= 1.8.5"])
      s.add_runtime_dependency(%q<rack>.freeze, [">= 2.0.6"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
    else
      s.add_dependency(%q<mongoid>.freeze, [">= 6.0"])
      s.add_dependency(%q<nokogiri>.freeze, [">= 1.8.5"])
      s.add_dependency(%q<rack>.freeze, [">= 2.0.6"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>.freeze, [">= 6.0"])
    s.add_dependency(%q<nokogiri>.freeze, [">= 1.8.5"])
    s.add_dependency(%q<rack>.freeze, [">= 2.0.6"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
  end
end

